// Dev seed: inserts ~40 clearly marked sample jobs ("[Sample]", dedupe_key "seed:N").
// Data only — never touches the schema. Safe to re-run (upserts).
//
//   pnpm seed         insert or refresh sample jobs
//   pnpm seed:clean   delete every sample job and its links/applications
//
// Dev and production share one database, so sample jobs show up in production
// too. Run `pnpm seed:clean` before relying on real data.

import { createClient } from "@supabase/supabase-js";
import type { Database } from "../src/lib/db/database.types";
import {
  LOCATION_BUCKETS,
  ROLE_TRACKS,
  WORK_MODES,
  type LocationBucket,
  type RoleTrack,
} from "../src/lib/db/domain";

const COUNT = 40;
const SEED_PREFIX = "seed:";
const HOUR_MS = 60 * 60 * 1000;

function fail(message: string): never {
  console.error(message);
  process.exit(1);
}

if (process.env.NODE_ENV === "production") {
  fail("Refusing to seed with NODE_ENV=production.");
}
const url = process.env.SUPABASE_URL;
const key = process.env.SUPABASE_SERVICE_ROLE_KEY;
if (!url || !key)
  fail("Set SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY in .env.local.");

const db = createClient<Database>(url, key, {
  auth: { persistSession: false, autoRefreshToken: false },
});

const TITLES: Record<RoleTrack, string[]> = {
  java_backend: [
    "Java Backend Engineer",
    "Spring Boot Developer",
    "Backend Engineer (Java)",
  ],
  ml_ai: ["ML Engineer", "Applied AI Engineer", "GenAI Developer"],
  data: ["Data Engineer", "Analytics Engineer", "Data Analyst"],
  full_stack: [
    "Full Stack Developer",
    "Software Engineer (React/Node)",
    "Product Engineer",
  ],
  other: ["Software Engineer", "Platform Engineer", "QA Automation Engineer"],
};

const SKILLS: Record<RoleTrack, string[]> = {
  java_backend: [
    "Java",
    "Spring Boot",
    "Kafka",
    "PostgreSQL",
    "Docker",
    "AWS",
    "Redis",
    "gRPC",
  ],
  ml_ai: [
    "Python",
    "PyTorch",
    "LLMs",
    "RAG",
    "LangChain",
    "SQL",
    "MLOps",
    "AWS",
  ],
  data: ["SQL", "Python", "Spark", "Airflow", "dbt", "Snowflake", "Kafka"],
  full_stack: [
    "TypeScript",
    "React",
    "Node.js",
    "Next.js",
    "PostgreSQL",
    "Docker",
    "GraphQL",
  ],
  other: ["Go", "Kubernetes", "Terraform", "Linux", "CI/CD"],
};

const LOCATIONS: Record<LocationBucket, string> = {
  pune: "Pune, Maharashtra",
  mumbai: "Mumbai, Maharashtra",
  gujarat: "Ahmedabad, Gujarat",
  remote_india: "Remote, India",
  remote_international: "Remote (EU timezone)",
  other: "Bengaluru, Karnataka",
};

const COMPANIES = [
  "Acme Corp",
  "Globex Labs",
  "Initech",
  "Umbrella Analytics",
  "Hooli",
  "Stark Digital",
  "Wayne Systems",
  "Pied Piper",
];

function pick<T>(list: readonly T[], i: number): T {
  return list[i % list.length] as T;
}

function sampleJobs(now: number) {
  return Array.from({ length: COUNT }, (_, i) => {
    const track = pick(ROLE_TRACKS, i);
    const bucket = pick(LOCATION_BUCKETS, i * 7);
    const skills = SKILLS[track];
    // Salary states rotate: meets min, below min, text without numbers, undisclosed.
    const salary = [
      {
        salary_text: "₹12–18 LPA",
        salary_min_lpa: 12,
        salary_max_lpa: 18,
        salary_meets_min: true,
      },
      {
        salary_text: "₹5–7 LPA",
        salary_min_lpa: 5,
        salary_max_lpa: 7,
        salary_meets_min: false,
      },
      {
        salary_text: "Competitive",
        salary_min_lpa: null,
        salary_max_lpa: null,
        salary_meets_min: null,
      },
      {
        salary_text: null,
        salary_min_lpa: null,
        salary_max_lpa: null,
        salary_meets_min: null,
      },
    ][i % 4]!;
    const yoe = [
      { min_yoe: 1, max_yoe: 3 },
      { min_yoe: 2, max_yoe: null },
      { min_yoe: null, max_yoe: 3 },
      { min_yoe: null, max_yoe: null },
    ][i % 4]!;
    // First six jobs are "new today"; the rest spread over ~40 days.
    const hoursAgo = i < 6 ? i * 3 + 1 : i * 24;
    const firstSeen = new Date(now - hoursAgo * HOUR_MS);
    const posted =
      i % 5 === 4
        ? null
        : new Date(firstSeen.getTime() - (i % 3) * 24 * HOUR_MS);

    return {
      dedupe_key: `${SEED_PREFIX}${i}`,
      title: `[Sample] ${pick(TITLES[track], i)}`,
      company: pick(COMPANIES, i * 3),
      location: LOCATIONS[bucket],
      location_bucket: bucket,
      work_mode: pick(WORK_MODES, i * 5),
      employment_type: i % 6 === 5 ? "Contract" : "Full-time",
      role_track: track,
      ...yoe,
      ...salary,
      skills: skills.slice(0, 3 + (i % (skills.length - 2))),
      summary:
        `Sample posting generated by the dev seed script.\n\n` +
        `You'd work on ${skills.slice(0, 3).join(", ")} in a small product team.`,
      apply_url: `https://example.com/seed/apply/${i}`,
      posted_at: posted ? posted.toISOString().slice(0, 10) : null,
      fit_score: i % 11 === 10 ? null : 5 - (i % 6),
      fit_reason:
        i % 11 === 10 ? null : `Matches ${skills.slice(0, 2).join(" and ")}.`,
      is_active: i % 13 !== 12,
      first_seen_at: firstSeen.toISOString(),
      last_seen_at: new Date(
        now - Math.min(hoursAgo, 12) * HOUR_MS,
      ).toISOString(),
    };
  });
}

async function seed() {
  const { data: sources, error: sourcesError } = await db
    .from("sources")
    .select("id")
    .order("id");
  if (sourcesError) throw sourcesError;
  if (sources.length === 0)
    fail("No sources exist; add one in Settings first.");

  const { data: jobs, error } = await db
    .from("jobs")
    .upsert(sampleJobs(Date.now()), { onConflict: "dedupe_key" })
    .select("id, dedupe_key");
  if (error) throw error;

  const links = jobs.flatMap((job) => {
    const i = Number(job.dedupe_key.slice(SEED_PREFIX.length));
    const ids = [
      pick(sources, i).id,
      ...(i % 3 === 0 ? [pick(sources, i + 1).id] : []),
    ];
    return [...new Set(ids)].map((sourceId) => ({
      job_id: job.id,
      source_id: sourceId,
      url: `https://example.com/seed/${sourceId}/${i}`,
      external_id: `seed-${i}`,
    }));
  });
  const { error: linkError } = await db
    .from("job_sources")
    .upsert(links, { onConflict: "url" });
  if (linkError) throw linkError;

  console.log(
    `Seeded ${jobs.length} sample jobs with ${links.length} source links.`,
  );
}

async function clean() {
  const { data: jobs, error } = await db
    .from("jobs")
    .select("id")
    .like("dedupe_key", `${SEED_PREFIX}%`);
  if (error) throw error;
  const ids = jobs.map((j) => j.id);
  if (ids.length === 0) {
    console.log("No sample jobs to remove.");
    return;
  }
  for (const table of ["applications", "job_sources"] as const) {
    const { error: e } = await db.from(table).delete().in("job_id", ids);
    if (e) throw e;
  }
  const { error: jobsError } = await db.from("jobs").delete().in("id", ids);
  if (jobsError) throw jobsError;
  console.log(`Removed ${ids.length} sample jobs.`);
}

(process.argv.includes("--clean") ? clean() : seed()).catch(
  (error: unknown) => {
    console.error(error);
    process.exit(1);
  },
);
